apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
  creationTimestamp: "2024-02-16T13:02:26Z"
  generation: 5
  labels:
    app: swiftserve-building
  name: swiftserve-building
  namespace: default
  resourceVersion: "8449127"
  uid: e7d9003f-687c-4263-b8c8-768fe3e90cb9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: swiftserve-building
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-02-18T09:25:30Z"
      creationTimestamp: null
      labels:
        app: swiftserve-building
    spec:
      containers:
      - image: shabbirdocks/swift-builds-stuff:3
        imagePullPolicy: IfNotPresent
        name: swift-builds-stuff
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-16T13:02:26Z"
    lastUpdateTime: "2024-02-18T09:25:32Z"
    message: ReplicaSet "swiftserve-building-87d79c8dd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-02-26T18:15:43Z"
    lastUpdateTime: "2024-02-26T18:15:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
