apiVersion: v1
kind: Service
metadata:
  labels:
    app: swiftserve-cloning
  name: swiftserve-cloning
  namespace: default
spec:
  ports:
  - nodePort: 30833
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: swiftserve-cloning
  sessionAffinity: None
  type: LoadBalancer